### ISSUE TITLE
Suggestion for room names in data directory

### ISSUE THREAD

**Issue by dfmorrison** [nodeGame/nodegame#12]
It would be nice if the numbers on the subdirectories of the data directory were more digits (at least four, maybe even five or six), with leading zeros. For example, instead of room7 have room00007. This way they'd sort in tidier fashion.

**Comment by shakty** [comment]
I see its utility. It is actually quite easy to implement, if you know where to look for, that is line 434 of file ServerChannel.

https://github.com/nodeGame/nodegame-server/blob/v4/lib/ServerChannel.js#L434

What you need is just a padding function like this:

https://stackoverflow.com/questions/10073699/pad-a-number-with-leading-zeros-in-javascript

Do you want to have a go when you have time? Since this is part of nodegame-server, you don't need to rebuild anything to try it.

If you want to make it fancier, you could have an option for how many leading 0 you would like, but that's involves a bit more coding and internal knowledge of nodeGame.

**Comment by shakty** [comment]
Done!
