### ISSUE TITLE
Function signature of widget methods?

### ISSUE THREAD

**Issue by lieuzhenghong** [nodeGame/nodegame#127]
Am looking at the [Widgets Methods v5](https://github.com/nodeGame/nodegame/wiki/Widgets-Methods-v5) wiki page; would like to modify a widget's text after it is loaded using a callback function. However, I don't have any idea what the function signature of the functions are. For instance, I would like to call 

```javascript
        var end_widget = node.widgets.lastAppended;
        console.log("This should trigger");
        console.log(end_widget)
        console.log(end_widget.getText('message'))
        end_widget.setText('message', 'New message here')
```

but as I am not sure what the setText function signature is, I'm not sure how to do so.

**Comment by lieuzhenghong** [comment]
After trial-and-error, I figured out how the `setText` method works. I have edited the widget methods v5 wiki to read as follows:

> `setText(requestedText, newText)`: Checks the value of `requestedText` and assigns the value of `newText` to it for display.

**Comment by shakty** [comment]
Thanks for updating the wiki, I will keep this issue open, so that I remember to add a better description to the other methods as well.

In the future, when the wiki isn't helping and you need to the know the internals of a function, you can simply do `console.log(someFunction.toString())` to visualize it.
