### ISSUE TITLE
Balanced treatments/allocation according to subjects' features

### ISSUE THREAD

**Issue by JKRhb** [nodeGame/nodegame#139]
Hi! 

I discovered nodeGame only recently and think it solves a lot of issues other frameworks have quite elegantly. So far, however, I wasn't able to figure out how to implement two elements of a study that are very important to me:

- Is it possible to ensure that all treatments contain the same number of participants/groups? Or, in general, can you limit the number of people assigned to a treatment? 
- Can you allocate people to treatments until a certain quota of (e. g. sociodemographic) features is fulfilled? My goal would be to have two treatment groups, each containing the same distribution of age, gender, and income as the general population, for example. A possible solution I was thinking of was to have two levels where the first one contains the sociodemographic questions which are then used to allocate or drop participants in the waiting room of level 2.

Thanks in advance and kind regards

Jan

**Comment by shakty** [comment]
Hi Jan,

Thanks for your nice words and for posting this issue. Please consider also the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/nodegame) for explanations about the nodeGame framework.

The wating room by default balances the number of people per treatment. However, it does not take into account dropouts. This isn't trivial and it is depending on the type of game, but it can be mitigated or fixed with some custom code.

The waiting room allows to write your own assignment function in which you can assign more people to a treatment and less to another. It is the CHOSEN_TREATMENT in file [waitroom.settings](https://github.com/nodeGame/nodegame/wiki/Waiting-Room-v5).

As you suggested, in order to do stratified assignment, you need to collect some demographics first, in a custom [level](https://github.com/nodeGame/nodegame/wiki/Game-Advanced-v5#levels-folder). Basically, on the first level they go through a survey independently, and on the second level there is the waiting room assigning them to treatments depending on their previous answers. You will need to write a little bit of code but it is rather easy. 

To this regard, the options `PLAYER_SORTING` and `PLAYER_GROUPING` might be useful. But you might want to write a small custom assignment function. 

Let me know if you need more help to implement your actual design.

Cheers,
Stefano

**Comment by shakty** [comment]
Closing it, but if you have other questions feel free to open a new one.
