### ISSUE TITLE
6.0.2 failing to run games

### ISSUE THREAD

**Issue by jjensenius3** [nodeGame/nodegame#147]
Hi Stefano,
With a fresh install of 6.0.2, nodegame is failing to run the ultimatum game. No error server-side, but client browser reports "index.js:12 Uncaught ReferenceError: node is not defined at window.onload (index.js:12)". This does not appear to be Ultimatum game specific.

This is present with both the standard install and also when using @dev during install.

**Comment by shakty** [comment]
Hi John,

Thanks for reporting this! It seems that the stable version got a corrupt
build of nodegame-full.js. However, the dev version works fine (it might
not work for you due to caching by the browser). I will fix it asap, in the
meantime you can rebuild the client:

node launcher -b

and it will work.

Best,
Stefano

**Comment by jjensenius3** [comment]
Thanks Stefano! Can confirm that rebuilding launcher worked.

**Comment by shakty** [comment]
Great! In the meantime it is already 6.0.3 :)

Am Fr., 30. Okt. 2020 um 16:08 Uhr schrieb John Jensenius <
notifications@github.com>:
